name: Ejecutar recolector cada hora

on:
  schedule:
    - cron: '0 * * * *'  # Cada hora
  workflow_dispatch:     # Permite ejecutarlo manualmente

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Crear archivo .env
        run: |
          echo "API_KEY=${{ secrets.API_KEY }}" >> .env
          echo "CIUDAD=${{ secrets.CIUDAD }}" >> .env
          echo "UNIDADES=${{ secrets.UNIDADES }}" >> .env

      - name: Ejecutar recolector
        run: python recolector.py
